language: node_js
sudo: true
node_js:
  - 6
  - 8
matrix:
  allow_failures:
    - node_js: 5
services: 
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - apt-get update
